"""Remove due date from AllocatedChore

Revision ID: 8385fb413b0e
Revises: 0b6591d01a05
Create Date: 2025-01-26 14:53:02.118343

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8385fb413b0e'
down_revision = '0b6591d01a05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('allocated_chores', schema=None) as batch_op:
        batch_op.drop_column('due_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('allocated_chores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('due_date', sa.DATE(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
