"""Remove delta duration from household member

Revision ID: 911d958d8f48
Revises: b3795ff72200
Create Date: 2025-01-30 19:51:42.161121

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '911d958d8f48'
down_revision = 'b3795ff72200'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('household_members', schema=None) as batch_op:
        batch_op.drop_column('delta_duration')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('household_members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('delta_duration', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text("'0'::double precision"), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
