"""Add delta_duration to household member

Revision ID: b3795ff72200
Revises: 956a7c4d0d9f
Create Date: 2025-01-29 23:52:08.564922

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import table, column
from sqlalchemy import Float

# revision identifiers, used by Alembic.
revision = 'b3795ff72200'
down_revision = '956a7c4d0d9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('household_members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('delta_duration', sa.Float(), nullable=False, server_default='0.0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('household_members', schema=None) as batch_op:
        batch_op.drop_column('delta_duration')

    # ### end Alembic commands ###
