"""Add last run to chore and household for chore scheduling

Revision ID: c83368419b5a
Revises: f11fe9d67c56
Create Date: 2025-01-27 19:13:38.806627

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c83368419b5a'
down_revision = 'f11fe9d67c56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_scheduled', sa.DateTime(), nullable=True))

    with op.batch_alter_table('households', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_run_chore_allocation', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('households', schema=None) as batch_op:
        batch_op.drop_column('last_run_chore_allocation')

    with op.batch_alter_table('chores', schema=None) as batch_op:
        batch_op.drop_column('last_scheduled')

    # ### end Alembic commands ###
