"""Update chore rating and allocated chore tables

Revision ID: d7dbb9fbdf3c
Revises: 1526da886f55
Create Date: 2025-01-25 22:28:24.194273

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7dbb9fbdf3c'
down_revision = '1526da886f55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('household_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('household_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('household_id', 'user_id', name='unique_household_member')
    )
    op.drop_table('household_member')
    with op.batch_alter_table('allocated_chores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Household_member_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('allocated_chores_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'household_members', ['Household_member_id'], ['id'])
        batch_op.drop_column('user_id')

    with op.batch_alter_table('chore_ratings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('household_member_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('chore_ratings_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'household_members', ['household_member_id'], ['id'])
        batch_op.drop_column('user_id')

    with op.batch_alter_table('chores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('household_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'households', ['household_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chores', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('household_id')

    with op.batch_alter_table('chore_ratings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('chore_ratings_user_id_fkey', 'users', ['user_id'], ['id'])
        batch_op.drop_column('household_member_id')

    with op.batch_alter_table('allocated_chores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('allocated_chores_user_id_fkey', 'users', ['user_id'], ['id'])
        batch_op.drop_column('Household_member_id')

    op.create_table('household_member',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('household_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], name='household_member_household_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='household_member_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='household_member_pkey'),
    sa.UniqueConstraint('household_id', 'user_id', name='unique_household_member')
    )
    op.drop_table('household_members')
    # ### end Alembic commands ###
