"""Make due date nullable on allocated chores

Revision ID: f11fe9d67c56
Revises: 8385fb413b0e
Create Date: 2025-01-26 15:00:40.542492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f11fe9d67c56'
down_revision = '8385fb413b0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('allocated_chores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('due_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('allocated_chores', schema=None) as batch_op:
        batch_op.drop_column('due_date')

    # ### end Alembic commands ###
